name: Build Container

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build Containers
    runs-on: jetson-orin-cahlen
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure Build X
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Latest
      - name: Builds Latest
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/store-genius/xibo-xmr:latest
          platforms: linux/amd64,linux/arm64
          build-args: GIT_COMMIT=${{ github.sha }}
          push: true
          load: false
